### ISSUE TITLE
Weather data local storage and caching

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#1]
Weather data, including observational data, daily summaries, and weather normals often need to be collected for building performance analysis. Because needs across the library will vary widely - with some users performing statewide or nationwide studies and other users performing analyses on only one or two projects - data caching and storage must be efficient enough to work at scale or across multiple machines without being so cumbersome that it scares away users with simpler needs. We need to develop a flexible weather data caching strategy.

**Comment by philngo** [comment]
We might consider something similar to the nltk data strategy.

For instance, in nltk, to get the data, you run the following command once to download a bunch of files to a specific directory on your computer (with reasonable default locations for this directory):

```
>>> import nltk
>>> nltk.download()
```

We may want to do something similar, either with flat files, as was done in NTLK, or within a database. If we use the database route, sqlite3 would be a good default, to make things easily accessible; but we could also (and should also) allow connections to local or remote postgres or mysql databases. The user would then need to configure an environment variable or a setting to access the data.

**Comment by philngo** [comment]
A completely different (and perhaps better) strategy would be not to attempt to pre-populate the database, but instead lazily cache or store any data pulled from an API.

**Comment by philngo** [comment]
This should "just work" upon pip install of library. Maybe it should look for a specific environment variable that tells it where to find the database; if the database is available, use it; otherwise, don't cache.

**Comment by potash** [comment]
look into https://pypi.python.org/pypi/pyfscache for caching of downloaded files

**Comment by philngo** [comment]
I don't think that's quite what we want - pyfscache caches the results of calling functions with particular arguments; it doesn't look particularly handy (out of the box) for caching and reloading whole downloaded files.

**Comment by philngo** [comment]
544c6961fb5402543ae92e1db87202bb4bee722c adds basic caching support for the `GSODWeatherSource`.

**Comment by philngo** [comment]
dbc2c269593823ac7402b6e9647b28b9bf35a317 adds basic caching support for `TMY3WeatherSource` and refactors code.

**Comment by philngo** [comment]
024f598c37077462ffcc1a493dcf115ad394cefe adds caching support for `ISDWeatherSource`
