### ISSUE TITLE
Update PRISM model to use appropriate regression method

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#12]
Right now it uses a global optimization of parameters.

**Comment by jgagliano** [comment]
what do you mean by "appropriate"? HO,CO,HC, or baseload only? if so, this is what we were talking about on our last call.  Brute force will take longer and possibly find a best fit that is nonsensical for that home (eg cooling end-use on gas).  this is a big discussion with lots of logic and decision trees.

**Comment by philngo** [comment]
Model selection will also be very important. Probably a bit ambitious to try to solve this in a single github issue. We're starting with checking goodness of fit on the various models (HO/CO/HC/baseload) to help prevent using nonsensical models.

**Comment by philngo** [comment]
Closed because it's too broad. See issues #52, #53.
