### ISSUE TITLE
Create a model that conforms to the ANSI BPI-2400 specification

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#13]
See the specification linked in the docs.

**Comment by jgagliano** [comment]
Phil

Which section of the std are you referring to. I co-authored it, so i should be able to help you.

**Comment by philngo** [comment]
Thanks, Jerone! We want the Open EE Meter to be as helpful as possible at any point in the process of calculating savings, so I thought maybe we would start with the following aspects of the standard, which are both very straightforward:
1. verifying whether or not utility bills meet the requirements for detailed calibration (3.2.2)
2. verifying that all the detailed (or simplified) model calibration acceptance criteria are met (3.4)

From there, although we aren't planning to create any sort of complex engineering models in the near future, I do think that in order to get as close as possible to completing a system that spits out a final qualified savings estimate, we would be interested developing out connections to third party software which can use its calibrated pre-retrofit and post-retrofit models to produce savings estimates.

One way or another, implementing as much of the standard as we can will help inform the process of calculating portfolio-level savings as accurately as possible even when such detailed information is widely unavailable.

**Comment by jgagliano** [comment]
Ok, so it sounds like you understand what you need to do and the algorithms are spelled out in the standard. If you need interpretation of the standard or have questions, let me know.

Jerone

**Comment by philngo** [comment]
0f29cce76199c5165591239e8b6163473a0759c6 is a start at implementing section 3.2.2 - verifying quality and completeness utility bill data in conjunction with heating degree days and cooling degree days for electricity and natural gas.

**Comment by philngo** [comment]
756476d709f7937599adbd0afca3eb29fa549b03 completes an implementation of section 3.2.2. Closing this issue and opening a new one specifically for section 3.4 (#63). Plan: open new issues for specific sections of the BPI2400 spec.
