### ISSUE TITLE
Plotting and visualization

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#40]
Where should this fit in? It would be nice to be able to visualize projects and model parameters.

**Comment by bryangoodrich** [comment]
I'm thinking `eemeter.visualize` could be a module containing all the visualization options and seems natural. But I agree, built-in visualizations would go a long way for data discovery and model evaluation, and providing your own framework for using the eemeter objects will make it easier for analysts to use them or build reports off of them in a consistent way.

**Comment by philngo** [comment]
Great suggestion. I'm sure we'll be able to factor out some visualization methods into a module like `eemeter.visualize`. We'll have to think carefully about how to design the interface to handle model-specific visualizations (e.g. various temperature sensitivity models).

**Comment by philngo** [comment]
This is the purpose of the oeem-client, so we'll close this issue. Let's reawaken if there's need to have better graphing utilities at the eemeter level.
