### ISSUE TITLE
Good resource to add to docs

### ISSUE THREAD

**Issue by jgagliano** [impactlab/eemeter#47]
NREL's Uniform Methods 
http://energy.gov/sites/prod/files/2013/11/f5/53827-8.pdf

We should make sure the OEEM is inline with this. sorry i don't know how to add this to docs page

**Comment by philngo** [comment]
Thanks - I'll take a look at it and add it to the docs along with the link to the other standards we reference

**Comment by philngo** [comment]
1ce25df9003f8b135ec76a751a25a9fd5755c65c updated docs
