### ISSUE TITLE
No model fitness criteria.

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#53]
One of the reasons the PRISM implementation doesn't check for model fitness is that we haven't yet implemented any model fitness criteria. We might start with implementing the Coefficient of Variation of Root Mean Square Error (CVRMSE).

**Comment by philngo** [comment]
Added CVRMSE

**Comment by jgagliano** [comment]
Great! Also should have R2 and the flatness index that PRISM defines.  Then we can use a combination of these metrics to determine quality of regressions following PRISM.  Do you have the PRISM documentation?

**Comment by philngo** [comment]
This is the main doc I've been referencing http://www.marean.mycpanel.princeton.edu/~marean/images/prism_intro.pdf

There are probably others I should be aware of - are you thinking of a specific document?

**Comment by jgagliano** [comment]
Yeah the actual PRISM reference documentation only exists as a paperback book.  We should figure out how to get ours scanned in and make available.

**Comment by philngo** [comment]
That would be extraordinarily helpful. Let me know if you're able to do that

**Comment by potash** [comment]
I've put a request in to Interlibrary Loan for a copy of Miriam Goldberg's dissertation "A Geometrical Approach to Non-differentiable Regression Models as Related to Methods for Assessing Residential Energy Conservation." Based on the citations of it in the Robust PRISM paper it should be quite useful to us.
