### ISSUE TITLE
Add CZ2010 weather normal support

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#66]
CZ2010 data may have to be stored externally or locally. It's available for free for download from http://weather.whiteboxtechnologies.com/wd-CZ2010 (must provide contact info to be able to download).

**Comment by jgagliano** [comment]
It is also available for free with no sign in at the caltrack.org site
http://www.caltrack.org/weather.html

**Comment by philngo** [comment]
9df8384277bdf8054b756a49fcaed2d72f5d20f5 adds support for importing CZ2010 data from CSV
