### ISSUE TITLE
"ConsumptionHistory" might contain estimates of future consumption

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#76]
If this happens, the consumption history name doesn't make too much sense.

**Comment by jgagliano** [comment]
Agree. Does not make sense. Including estimated meter readings is a must, however, I meter (measuring device) should never contain future projections are estimates.  That is for the model of the meter.

Sent from my Verizon Wireless 4G LTE DROID

Phil Ngo notifications@github.com wrote:

If this happens, the consumption history name doesn't make too much sense.

—
Reply to this email directly or view it on GitHubhttps://github.com/impactlab/eemeter/issues/76.

IMPORTANT NOTICE: This email message is intended to be received only by persons entitled to receive the confidential information it may contain. Email messages to clients of Performance Systems Development may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system.

**Comment by philngo** [comment]
The Consumption and ConsumptionHistory objects have been replaced with a ConsumptionData object.
