### ISSUE TITLE
Mapping zipcode to weather station

### ISSUE THREAD

**Issue by philngo** [impactlab/eemeter#87]
The modules currently maps from zipcode to weather station by grabbing the nearest weather station - convert both to lat long, then measure distance using the haversine method.

Some stakeholders may be interested in more sophisticated mapping methods.

**Comment by potash** [comment]
Or instead of using a single weather station we might use multiple stations for estimations using an interpolation method like Kriging.

**Comment by philngo** [comment]
This was implemented in v0.2.13-alpha
